import offerslide from "./components/js/offer.js";
offerslide();
import menn from "./components/js/men.js";
menn();
import menu from "./components/js/menusm";
menu();
import s01 from "./components/js/section01";
s01();
import s02 from "./components/js/section02";
s02();
import s03 from "./components/js/section03";
s03();
import s03sm from "./components/js/section03sm";
s03sm();
import s04 from "./components/js/section04";
s04();
import s04sm from "./components/js/section04sm";
s04sm();
import s05 from "./components/js/section05.js";
s05();
import s05sm from "./components/js/section05sm";
s05sm();
import s06 from "./components/js/section06";
s06();
import s06sm from "./components/js/section06sm";
s06sm();
import s07 from "./components/js/section07.js";
s07();
import s10 from "./components/js/section10.js";
s10();
import footer from "./components/js/footer.js";
footer();